import pygame
from pygame.locals import *
import os


SC_WIDTH, SC_HEIGHT = (800,608)
SC_SIZE = (SC_WIDTH,SC_HEIGHT)
SC_CENTER = (SC_WIDTH//2, SC_HEIGHT//2)

DISPLAY_WIDTH, DISPLAY_HEIGHT = (400,304)
DISPLAY_SIZE = (DISPLAY_WIDTH, DISPLAY_HEIGHT)

FPS = 60

BG_POS = (0,0)




MAX_VERTICAL_ACCELERATION = 5